### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by thomaswinckell** [thomaswinckell/reactfire-white-board-website#3]
Please use only one font. The "Roboto, sans-serif" seems to be good.

**Comment by CremAlex** [comment]
I chose to put a link to [googleFont](https://fonts.googleapis.com/css?family=Roboto:400,300,500,700) in the head of index.hmtl to get the font.

And I had a problem with the css. It seems I will have to find a way to ignore the css from the white-board because the css from the website couldn't overwrite the one from the module ...

So my temporary fix is to put Roboto in the white-board aswell

**Comment by thomaswinckell** [comment]
As you said, the website couldn't overwrite the one from the module, and that's good.
For the font, I was speaking about the website only. If you want to put a Roboto for the white board module, you can do it too.

**Comment by CremAlex** [comment]
Oh sorry I meant that the css from the module (body property for exemple) is taken in the website aswell. So when in the website's theme I changed the font to roboto. I still had on the website the font used in the module. 

In my opinion the board should not apply style on html, body but only on his own context

**Comment by thomaswinckell** [comment]
I misunderstood. You right ! Before we pack the whiteboard as a module, it was useful, but now no. So now, on the white board module side, you need to extract the global style of the whiteboard and put it in the demo folder. This style will still be useful for the demo of the module. Please create an issue on the whiteboard repository for that.
